services:
    mysql-database: {
        image: 'mysql:latest', 
        container_name: mysql-db, 
        environment: { 
           MYSQL_ROOT_PASSWORD: rootpassword, 
           MYSQL_PASSWORD: mypassword, 
           MYSQL_DATABASE: e-commarce-db, 
           MYSQL_USER: myuser 
        },
        volumes: ['mysql-volume:/var/lib/mysql'] 
    }
volumes:
    mysql-volume: { external: true }
