services:
  php-proxy:
    container_name: php-proxy
    build:
      context: .
      dockerfile: Dockerfile.PHP-Proxy
    ports:
      - "8000:80"
    networks:
      - php-app
    restart: always
    depends_on:
      - php-backend-fpm
  
  php-backend-fpm:
    container_name: php-backend-fpm
    build:
      context: .
      dockerfile: Dockerfile.PHP-FPM
    networks:
      - php-app
    
    restart: always
  #broker:
  #  image: apache/kafka:latest
  #  container_name: broker
  #  environment:
  #    KAFKA_NODE_ID: 1
  #    KAFKA_PROCESS_ROLES: broker,controller
  #    KAFKA_LISTENERS: PLAINTEXT://broker:9092,CONTROLLER://broker:9093
  #    KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
  #    KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
  #    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
  #    KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
  #    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #    KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  #    KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
  #    KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  #    KAFKA_NUM_PARTITIONS: 3
  #  networks:
  #    - php-app
  #  ports:
  #    - "9092:9092"
  #    - "9093:9093"
networks:
  php-app: